from petrisim.utils import *


class Mozhayskiy(Module):
	def __init__(self, name: str = None):
		if not name:
			name = __class__.__name__
		super().__init__(name)

	def build_net_structure(self) -> PetriNet:

		# petri nets
		recipient_0_net = PetriNet("recipient_0_net", timescale=1)
		donor_0_net = PetriNet("donor_0_net", timescale=1)
		mozhayskiy_net = PetriNet("mozhayskiy_net", timescale=1)

		# recipient_0_net places
		recipient_0_net.add_place(Place("T0_plasmid_molecule"))
		recipient_0_net.add_place(Place("T0_protein_molecule"))
		recipient_0_net.add_place(Place("T2_protein_molecule"))
		recipient_0_net.add_place(Place("T5_protein_molecule"))
		recipient_0_net.add_place(Place("T0_mod_protein_molecule"))
		recipient_0_net.add_place(Place("T1_plasmid_molecule"))
		recipient_0_net.add_place(Place("T1_protein_molecule"))
		recipient_0_net.add_place(Place("T3_protein_molecule"))
		recipient_0_net.add_place(Place("T1_mod_protein_molecule"))
		recipient_0_net.add_place(Place("T2_plasmid_molecule"))
		recipient_0_net.add_place(Place("S1_molecule"))
		recipient_0_net.add_place(Place("T2_mod_protein_molecule"))
		recipient_0_net.add_place(Place("T3_plasmid_molecule"))
		recipient_0_net.add_place(Place("T3_mod_protein_molecule"))
		recipient_0_net.add_place(Place("S2_molecule"))
		recipient_0_net.add_place(Place("T4_plasmid_molecule"))
		recipient_0_net.add_place(Place("T4_protein_molecule"))
		recipient_0_net.add_place(Place("T5_plasmid_molecule"))
		recipient_0_net.add_place(Place("T6_protein_molecule"))
		recipient_0_net.add_place(Place("T5_mod_protein_molecule"))
		recipient_0_net.add_place(Place("T6_plasmid_molecule"))
		recipient_0_net.add_place(Place("T4_plasmid_strand_molecule"))
		recipient_0_net.add_place(Place("T5_plasmid_strand_molecule"))
		recipient_0_net.add_place(Place("T6_plasmid_strand_molecule"))
		recipient_0_net.add_place(Place("T4_mod_protein_molecule"))
		recipient_0_net.add_place(Place("T6_mod_protein_molecule"))

		# recipient_0_net transitions
		recipient_0_net.add_transition(Transition("process_21"))
		recipient_0_net.add_transition(Transition("process_22"))
		recipient_0_net.add_transition(Transition("process_23"))
		recipient_0_net.add_transition(Transition("process_24"))
		recipient_0_net.add_transition(Transition("process_25"))
		recipient_0_net.add_transition(Transition("process_26"))
		recipient_0_net.add_transition(Transition("process_27"))
		recipient_0_net.add_transition(Transition("process_28"))
		recipient_0_net.add_transition(Transition("process_29"))
		recipient_0_net.add_transition(Transition("process_30"))
		recipient_0_net.add_transition(Transition("process_31"))
		recipient_0_net.add_transition(Transition("process_32"))
		recipient_0_net.add_transition(Transition("process_33"))
		recipient_0_net.add_transition(Transition("process_34"))
		recipient_0_net.add_transition(Transition("T5_plasmid_molecule_inhibition_T4_protein_molecule_2"))
		recipient_0_net.add_transition(Transition("T5_plasmid_molecule_inhibition_T6_protein_molecule_2"))
		recipient_0_net.add_transition(Transition("process_35"))
		recipient_0_net.add_transition(Transition("process_36"))
		recipient_0_net.add_transition(Transition("process_37"))
		recipient_0_net.add_transition(Transition("T4_plasmid_strand_molecule_inhibition_T4_plasmid_molecule_1"))
		recipient_0_net.add_transition(Transition("process_38"))
		recipient_0_net.add_transition(Transition("T5_plasmid_strand_molecule_inhibition_T5_plasmid_molecule_1"))
		recipient_0_net.add_transition(Transition("process_39"))
		recipient_0_net.add_transition(Transition("T6_plasmid_strand_molecule_inhibition_T6_plasmid_molecule_1"))
		recipient_0_net.add_transition(Transition("T0_protein_molecule_degradation_2"))
		recipient_0_net.add_transition(Transition("T1_protein_molecule_degradation_2"))
		recipient_0_net.add_transition(Transition("T2_protein_molecule_degradation_2"))
		recipient_0_net.add_transition(Transition("T3_protein_molecule_degradation_2"))
		recipient_0_net.add_transition(Transition("T4_protein_molecule_degradation_2"))
		recipient_0_net.add_transition(Transition("T5_protein_molecule_degradation_2"))
		recipient_0_net.add_transition(Transition("T6_protein_molecule_degradation_2"))
		recipient_0_net.add_transition(Transition("T0_mod_protein_molecule_degradation_2"))
		recipient_0_net.add_transition(Transition("T1_mod_protein_molecule_degradation_2"))
		recipient_0_net.add_transition(Transition("T2_mod_protein_molecule_degradation_2"))
		recipient_0_net.add_transition(Transition("T3_mod_protein_molecule_degradation_2"))
		recipient_0_net.add_transition(Transition("T4_mod_protein_molecule_degradation_2"))
		recipient_0_net.add_transition(Transition("T5_mod_protein_molecule_degradation_2"))
		recipient_0_net.add_transition(Transition("T6_mod_protein_molecule_degradation_2"))
		recipient_0_net.add_transition(Transition("S1_molecule_degradation_2"))
		recipient_0_net.add_transition(Transition("S2_molecule_degradation_2"))
		recipient_0_net.add_transition(Transition("T4_plasmid_strand_molecule_degradation_2"))
		recipient_0_net.add_transition(Transition("T5_plasmid_strand_molecule_degradation_2"))
		recipient_0_net.add_transition(Transition("T6_plasmid_strand_molecule_degradation_2"))

		# donor_0_net places
		donor_0_net.add_place(Place("T0_plasmid_molecule"))
		donor_0_net.add_place(Place("T0_protein_molecule"))
		donor_0_net.add_place(Place("T2_protein_molecule"))
		donor_0_net.add_place(Place("T5_protein_molecule"))
		donor_0_net.add_place(Place("T0_mod_protein_molecule"))
		donor_0_net.add_place(Place("T1_plasmid_molecule"))
		donor_0_net.add_place(Place("T1_protein_molecule"))
		donor_0_net.add_place(Place("T3_protein_molecule"))
		donor_0_net.add_place(Place("T1_mod_protein_molecule"))
		donor_0_net.add_place(Place("T2_plasmid_molecule"))
		donor_0_net.add_place(Place("S1_molecule"))
		donor_0_net.add_place(Place("T2_mod_protein_molecule"))
		donor_0_net.add_place(Place("T3_plasmid_molecule"))
		donor_0_net.add_place(Place("T3_mod_protein_molecule"))
		donor_0_net.add_place(Place("S2_molecule"))
		donor_0_net.add_place(Place("T4_plasmid_molecule"))
		donor_0_net.add_place(Place("T4_protein_molecule"))
		donor_0_net.add_place(Place("T5_plasmid_molecule"))
		donor_0_net.add_place(Place("T6_protein_molecule"))
		donor_0_net.add_place(Place("T5_mod_protein_molecule"))
		donor_0_net.add_place(Place("T6_plasmid_molecule"))
		donor_0_net.add_place(Place("pilus_molecule"))
		donor_0_net.add_place(Place("T4_plasmid_strand_molecule"))
		donor_0_net.add_place(Place("T5_plasmid_strand_molecule"))
		donor_0_net.add_place(Place("T6_plasmid_strand_molecule"))
		donor_0_net.add_place(Place("T4_mod_protein_molecule"))
		donor_0_net.add_place(Place("T6_mod_protein_molecule"))

		# donor_0_net transitions
		donor_0_net.add_transition(Transition("process_1"))
		donor_0_net.add_transition(Transition("process_2"))
		donor_0_net.add_transition(Transition("process_3"))
		donor_0_net.add_transition(Transition("process_4"))
		donor_0_net.add_transition(Transition("process_5"))
		donor_0_net.add_transition(Transition("process_6"))
		donor_0_net.add_transition(Transition("process_7"))
		donor_0_net.add_transition(Transition("process_8"))
		donor_0_net.add_transition(Transition("process_9"))
		donor_0_net.add_transition(Transition("process_10"))
		donor_0_net.add_transition(Transition("process_11"))
		donor_0_net.add_transition(Transition("process_12"))
		donor_0_net.add_transition(Transition("process_13"))
		donor_0_net.add_transition(Transition("process_14"))
		donor_0_net.add_transition(Transition("T5_plasmid_molecule_inhibition_T4_protein_molecule_1"))
		donor_0_net.add_transition(Transition("T5_plasmid_molecule_inhibition_T6_protein_molecule_1"))
		donor_0_net.add_transition(Transition("process_15"))
		donor_0_net.add_transition(Transition("process_16"))
		donor_0_net.add_transition(Transition("process_17"))
		donor_0_net.add_transition(Transition("process_18"))
		donor_0_net.add_transition(Transition("process_19"))
		donor_0_net.add_transition(Transition("process_20"))
		donor_0_net.add_transition(Transition("T0_protein_molecule_degradation_1"))
		donor_0_net.add_transition(Transition("T1_protein_molecule_degradation_1"))
		donor_0_net.add_transition(Transition("T2_protein_molecule_degradation_1"))
		donor_0_net.add_transition(Transition("T3_protein_molecule_degradation_1"))
		donor_0_net.add_transition(Transition("T4_protein_molecule_degradation_1"))
		donor_0_net.add_transition(Transition("T5_protein_molecule_degradation_1"))
		donor_0_net.add_transition(Transition("T6_protein_molecule_degradation_1"))
		donor_0_net.add_transition(Transition("T0_mod_protein_molecule_degradation_1"))
		donor_0_net.add_transition(Transition("T1_mod_protein_molecule_degradation_1"))
		donor_0_net.add_transition(Transition("T2_mod_protein_molecule_degradation_1"))
		donor_0_net.add_transition(Transition("T3_mod_protein_molecule_degradation_1"))
		donor_0_net.add_transition(Transition("T4_mod_protein_molecule_degradation_1"))
		donor_0_net.add_transition(Transition("T5_mod_protein_molecule_degradation_1"))
		donor_0_net.add_transition(Transition("T6_mod_protein_molecule_degradation_1"))
		donor_0_net.add_transition(Transition("S1_molecule_degradation_1"))
		donor_0_net.add_transition(Transition("S2_molecule_degradation_1"))
		donor_0_net.add_transition(Transition("pilus_molecule_degradation_1"))
		donor_0_net.add_transition(Transition("T4_plasmid_strand_molecule_degradation_1"))
		donor_0_net.add_transition(Transition("T5_plasmid_strand_molecule_degradation_1"))
		donor_0_net.add_transition(Transition("T6_plasmid_strand_molecule_degradation_1"))

		# mozhayskiy_net places
		mozhayskiy_net.add_place(Place("donor", [ donor_0_net ]))
		mozhayskiy_net.add_place(Place("recipient", [ recipient_0_net ]))

		# mozhayskiy_net transitions
		mozhayskiy_net.add_transition(Transition("juxtacrine_signaling_T4_plasmid_strand_molecule_donor_recipient_1", Expression("str(x) == 'T4_plasmid_strand_molecule'")))
		mozhayskiy_net.add_transition(Transition("juxtacrine_signaling_T5_plasmid_strand_molecule_donor_recipient_1", Expression("str(x) == 'T5_plasmid_strand_molecule'")))
		mozhayskiy_net.add_transition(Transition("juxtacrine_signaling_T6_plasmid_strand_molecule_donor_recipient_1", Expression("str(x) == 'T6_plasmid_strand_molecule'")))

		# mozhayskiy_net arcs
		mozhayskiy_net.add_input("donor", "juxtacrine_signaling_T4_plasmid_strand_molecule_donor_recipient_1", Variable('x'), notify=[donor_0_net])
		mozhayskiy_net.add_input("donor", "juxtacrine_signaling_T5_plasmid_strand_molecule_donor_recipient_1", Variable('x'), notify=[donor_0_net])
		mozhayskiy_net.add_input("donor", "juxtacrine_signaling_T6_plasmid_strand_molecule_donor_recipient_1", Variable('x'), notify=[donor_0_net])
		mozhayskiy_net.add_output("recipient", "juxtacrine_signaling_T4_plasmid_strand_molecule_donor_recipient_1", Expression('x.replace("protein", "receptor_active_protein")'), notify=[recipient_0_net])
		mozhayskiy_net.add_output("recipient", "juxtacrine_signaling_T5_plasmid_strand_molecule_donor_recipient_1", Expression('x.replace("protein", "receptor_active_protein")'), notify=[recipient_0_net])
		mozhayskiy_net.add_output("recipient", "juxtacrine_signaling_T6_plasmid_strand_molecule_donor_recipient_1", Expression('x.replace("protein", "receptor_active_protein")'), notify=[recipient_0_net])

		# donor_0_net arcs
		donor_0_net.add_input("T0_plasmid_molecule", "process_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T0_plasmid_molecule", "process_2", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T2_protein_molecule", "process_2", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T0_plasmid_molecule", "process_3", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T5_protein_molecule", "process_3", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T0_protein_molecule", "process_4", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T1_plasmid_molecule", "process_5", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T1_plasmid_molecule", "process_6", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T3_protein_molecule", "process_6", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T1_protein_molecule", "process_7", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T2_plasmid_molecule", "process_8", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T1_protein_molecule", "process_8", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T2_plasmid_molecule", "process_9", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("S1_molecule", "process_9", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T2_protein_molecule", "process_10", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("S1_molecule", "process_10", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T3_plasmid_molecule", "process_11", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("S1_molecule", "process_11", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T3_protein_molecule", "process_12", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("S2_molecule", "process_12", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T4_plasmid_molecule", "process_13", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("S1_molecule", "process_13", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T5_plasmid_molecule", "process_14", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("S2_molecule", "process_14", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T4_protein_molecule", "T5_plasmid_molecule_inhibition_T4_protein_molecule_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T5_plasmid_molecule", "T5_plasmid_molecule_inhibition_T4_protein_molecule_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T6_protein_molecule", "T5_plasmid_molecule_inhibition_T6_protein_molecule_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T5_plasmid_molecule", "T5_plasmid_molecule_inhibition_T6_protein_molecule_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T5_protein_molecule", "process_15", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T6_plasmid_molecule", "process_16", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("S1_molecule", "process_16", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("pilus_molecule", "process_17", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T4_plasmid_molecule", "process_18", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("pilus_molecule", "process_18", MultiArc([Value(dot)]*5), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T5_plasmid_molecule", "process_19", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("pilus_molecule", "process_19", MultiArc([Value(dot)]*5), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T6_plasmid_molecule", "process_20", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("pilus_molecule", "process_20", MultiArc([Value(dot)]*5), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T0_protein_molecule", "T0_protein_molecule_degradation_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T1_protein_molecule", "T1_protein_molecule_degradation_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T2_protein_molecule", "T2_protein_molecule_degradation_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T3_protein_molecule", "T3_protein_molecule_degradation_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T4_protein_molecule", "T4_protein_molecule_degradation_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T5_protein_molecule", "T5_protein_molecule_degradation_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T6_protein_molecule", "T6_protein_molecule_degradation_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T0_mod_protein_molecule", "T0_mod_protein_molecule_degradation_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T1_mod_protein_molecule", "T1_mod_protein_molecule_degradation_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T2_mod_protein_molecule", "T2_mod_protein_molecule_degradation_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T3_mod_protein_molecule", "T3_mod_protein_molecule_degradation_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T4_mod_protein_molecule", "T4_mod_protein_molecule_degradation_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T5_mod_protein_molecule", "T5_mod_protein_molecule_degradation_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T6_mod_protein_molecule", "T6_mod_protein_molecule_degradation_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("S1_molecule", "S1_molecule_degradation_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("S2_molecule", "S2_molecule_degradation_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("pilus_molecule", "pilus_molecule_degradation_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T4_plasmid_strand_molecule", "T4_plasmid_strand_molecule_degradation_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T5_plasmid_strand_molecule", "T5_plasmid_strand_molecule_degradation_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_input("T6_plasmid_strand_molecule", "T6_plasmid_strand_molecule_degradation_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T0_protein_molecule", "process_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T0_plasmid_molecule", "process_1", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T0_protein_molecule", "process_2", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T0_plasmid_molecule", "process_2", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T0_protein_molecule", "process_3", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T0_plasmid_molecule", "process_3", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T0_mod_protein_molecule", "process_4", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T1_protein_molecule", "process_5", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T1_plasmid_molecule", "process_5", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T1_protein_molecule", "process_6", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T1_plasmid_molecule", "process_6", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T1_mod_protein_molecule", "process_7", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T2_protein_molecule", "process_8", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T2_plasmid_molecule", "process_8", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T2_protein_molecule", "process_9", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T2_plasmid_molecule", "process_9", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T2_mod_protein_molecule", "process_10", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T3_protein_molecule", "process_11", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T3_plasmid_molecule", "process_11", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T3_mod_protein_molecule", "process_12", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T4_protein_molecule", "process_13", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T4_plasmid_molecule", "process_13", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T5_protein_molecule", "process_14", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T5_plasmid_molecule", "process_14", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T5_mod_protein_molecule", "process_15", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T6_protein_molecule", "process_16", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T6_plasmid_molecule", "process_16", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("pilus_molecule", "process_17", MultiArc([Value(dot)]*2), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T4_plasmid_strand_molecule", "process_18", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T4_plasmid_molecule", "process_18", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T5_plasmid_strand_molecule", "process_19", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T5_plasmid_molecule", "process_19", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T6_plasmid_strand_molecule", "process_20", Value(dot), notify=[mozhayskiy_net.place('donor')])
		donor_0_net.add_output("T6_plasmid_molecule", "process_20", Value(dot), notify=[mozhayskiy_net.place('donor')])

		# recipient_0_net arcs
		recipient_0_net.add_input("T0_plasmid_molecule", "process_21", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T0_plasmid_molecule", "process_22", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T2_protein_molecule", "process_22", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T0_plasmid_molecule", "process_23", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T5_protein_molecule", "process_23", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T0_protein_molecule", "process_24", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T1_plasmid_molecule", "process_25", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T1_plasmid_molecule", "process_26", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T3_protein_molecule", "process_26", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T1_protein_molecule", "process_27", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T2_plasmid_molecule", "process_28", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T1_protein_molecule", "process_28", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T2_plasmid_molecule", "process_29", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("S1_molecule", "process_29", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T2_protein_molecule", "process_30", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("S1_molecule", "process_30", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T3_plasmid_molecule", "process_31", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("S1_molecule", "process_31", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T3_protein_molecule", "process_32", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("S2_molecule", "process_32", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T4_plasmid_molecule", "process_33", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("S1_molecule", "process_33", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T5_plasmid_molecule", "process_34", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("S2_molecule", "process_34", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T4_protein_molecule", "T5_plasmid_molecule_inhibition_T4_protein_molecule_2", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T5_plasmid_molecule", "T5_plasmid_molecule_inhibition_T4_protein_molecule_2", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T6_protein_molecule", "T5_plasmid_molecule_inhibition_T6_protein_molecule_2", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T5_plasmid_molecule", "T5_plasmid_molecule_inhibition_T6_protein_molecule_2", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T5_protein_molecule", "process_35", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T6_plasmid_molecule", "process_36", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("S1_molecule", "process_36", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T4_plasmid_strand_molecule", "process_37", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T4_plasmid_molecule", "T4_plasmid_strand_molecule_inhibition_T4_plasmid_molecule_1", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T4_plasmid_strand_molecule", "T4_plasmid_strand_molecule_inhibition_T4_plasmid_molecule_1", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T5_plasmid_strand_molecule", "process_38", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T5_plasmid_molecule", "T5_plasmid_strand_molecule_inhibition_T5_plasmid_molecule_1", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T5_plasmid_strand_molecule", "T5_plasmid_strand_molecule_inhibition_T5_plasmid_molecule_1", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T6_plasmid_strand_molecule", "process_39", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T6_plasmid_molecule", "T6_plasmid_strand_molecule_inhibition_T6_plasmid_molecule_1", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T6_plasmid_strand_molecule", "T6_plasmid_strand_molecule_inhibition_T6_plasmid_molecule_1", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T0_protein_molecule", "T0_protein_molecule_degradation_2", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T1_protein_molecule", "T1_protein_molecule_degradation_2", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T2_protein_molecule", "T2_protein_molecule_degradation_2", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T3_protein_molecule", "T3_protein_molecule_degradation_2", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T4_protein_molecule", "T4_protein_molecule_degradation_2", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T5_protein_molecule", "T5_protein_molecule_degradation_2", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T6_protein_molecule", "T6_protein_molecule_degradation_2", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T0_mod_protein_molecule", "T0_mod_protein_molecule_degradation_2", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T1_mod_protein_molecule", "T1_mod_protein_molecule_degradation_2", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T2_mod_protein_molecule", "T2_mod_protein_molecule_degradation_2", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T3_mod_protein_molecule", "T3_mod_protein_molecule_degradation_2", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T4_mod_protein_molecule", "T4_mod_protein_molecule_degradation_2", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T5_mod_protein_molecule", "T5_mod_protein_molecule_degradation_2", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T6_mod_protein_molecule", "T6_mod_protein_molecule_degradation_2", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("S1_molecule", "S1_molecule_degradation_2", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("S2_molecule", "S2_molecule_degradation_2", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T4_plasmid_strand_molecule", "T4_plasmid_strand_molecule_degradation_2", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T5_plasmid_strand_molecule", "T5_plasmid_strand_molecule_degradation_2", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_input("T6_plasmid_strand_molecule", "T6_plasmid_strand_molecule_degradation_2", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T0_protein_molecule", "process_21", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T0_plasmid_molecule", "process_21", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T0_protein_molecule", "process_22", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T0_plasmid_molecule", "process_22", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T0_protein_molecule", "process_23", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T0_plasmid_molecule", "process_23", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T0_mod_protein_molecule", "process_24", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T1_protein_molecule", "process_25", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T1_plasmid_molecule", "process_25", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T1_protein_molecule", "process_26", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T1_plasmid_molecule", "process_26", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T1_mod_protein_molecule", "process_27", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T2_protein_molecule", "process_28", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T2_plasmid_molecule", "process_28", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T2_protein_molecule", "process_29", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T2_plasmid_molecule", "process_29", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T2_mod_protein_molecule", "process_30", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T3_protein_molecule", "process_31", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T3_plasmid_molecule", "process_31", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T3_mod_protein_molecule", "process_32", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T4_protein_molecule", "process_33", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T4_plasmid_molecule", "process_33", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T5_protein_molecule", "process_34", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T5_plasmid_molecule", "process_34", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T5_mod_protein_molecule", "process_35", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T6_protein_molecule", "process_36", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T6_plasmid_molecule", "process_36", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T4_plasmid_molecule", "process_37", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T5_plasmid_molecule", "process_38", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		recipient_0_net.add_output("T6_plasmid_molecule", "process_39", Value(dot), notify=[mozhayskiy_net.place('recipient')])
		return mozhayskiy_net
